import subprocess

flatpaks = [
    "com.spotify.Client",
    "com.bitwarden.desktop",
    "md.obsidian.Obsidian",
    "org.zotero.Zotero",
    "ar.com.tuxguitar.TuxGuitar",
    "io.podman_desktop.PodmanDesktop",
    "com.discordapp.Discord",
    "org.gimp.GIMP",
    "org.remmina.Remmina",
    "org.telegram.desktop",
    "com.visualstudio.code",
    "org.onlyoffice.desktopeditors",
    "cc.arduino.IDE2",
    "com.adrienplazas.Metronome",
    "com.authy.Authy",
    "com.github.alexkdeveloper.somafm",
    "com.github.jeromerobert.pdfarranger",
    "com.github.tchx84.Flatseal",
    "com.ticktick.TickTick",
    "de.haeckerfelix.Shortwave",
    "io.crow_translate.CrowTranslate",
    "io.dbeaver.DBeaverCommunity",
    "io.github.davidoc26.wallpaper_selector",
    "io.github.giantpinkrobots.flatsweep",
    "io.github.peazip.PeaZip",
    "io.gitlab.news_flash.NewsFlash",
    "com.ktechpit.wonderwall",
    "io.gitlab.zehkira.Monophony",
    "net.supertuxkart.SuperTuxKart",
    "org.gnome.World.PikaBackup",
    "org.apache.jmeter",
    "com.tutanota.Tutanota",
    "org.gnome.Logs",
    "com.ktechpit.colorwall",
    "org.zealdocs.Zeal",
    "org.inkscape.Inkscape",
    "com.ultimaker.cura",
    "org.wireshark.Wireshark",
    "org.zaproxy.ZAP",
    "org.videolan.VLC",
    "org.nmap.Zenmap",
    "net.pcsx2.PCSX2",
    "org.freecadweb.FreeCAD",
    "de.haeckerfelix.Fragments",
    "org.gaphor.Gaphor",
    "info.febvre.Komikku",
    "io.missioncenter.MissionCenter",
]

for flatpak in flatpaks:
    subprocess.run(["flatpak", "install", "-y", flatpak])
